

services:
  dashboard-crypto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard-crypto
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: flask run --host=0.0.0.0 --port=5000






  